In [139]:
from googletrans import Translator

In [140]:
import PyPDF2 
    
# creating a pdf file object 
pdfFileObj = open('PopupCaptcha.pdf', 'rb') 
    
# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 
    
# printing number of pages in pdf file 
print(pdfReader.numPages) 
    
# creating a page object 
pageObj = pdfReader.getPage(0) 
    
# extracting text from page 
 
    
# closing the pdf file object 
pdfFileObj.close()

42

In [141]:

f = {
    "1" : {
        "नाम": "दर्शन चौधरी",
        "Father": "हरवीर सिंह",
        "मकानसंख्या": 00,
        "आयु": 26,
        "लिंग": "पुरुष"
    },

    "2" : {
        "नाम": "राजकुमारी चौधरी",
        "Husband": "दर्शन चौधरी",
        "मकानसंख्या": 00,
        "आयु": 21,
        "लिंग": "महिला"
    },
    
    "3" : {
        "नाम": "कुवरपाली",
        "Husband": "पूरन सिंह",
        "मकानसंख्या": 1,
        "आयु": 75,
        "लिंग": "महिला",
    },
    "4" :{"नाम": "जयवीर",
     "Father": "पूरन सिंह",
     "मकानसंख्या": 1,
     "आयु": 47,
     "लिंग": "पुरुष"},
    "5" : {"नाम": "नेकराम",
     "Father": "पूरन सिंह",
     "मकानसंख्या": 1,
     "आयु": 45,
     "लिंग": "पुरुष"},
    "6" : {"नाम": "राजवती",
     "Husband": "जयवीर",
     "मकानसंख्या": 1,
     "आयु": 43,
     "लिंग": "महिला"},
    "7" : {"नाम": "मीता",
     "Husband": "नेकराम",
     "मकानसंख्या": 1,
     "आयु": 40,
     "लिंग": "महिला"},
    "8" : {"नाम":  "कर्मवीर",
     "Father": "पूरन",
     "मकानसंख्या": 1,
     "आयु": 3,
     "लिंग": "पुरुष"},
    "9" : {"नाम": "नीतू देवी",
     "Husband": "कर्मवीर",
     "मकानसंख्या": 2,
     "आयु": 35,
     "लिंग": "महिला"},
    "10" : {"नाम": "संगीता",
        "Husband": "सुनील कुमार",
        "मकानसंख्या": 2,
        "आयु": 36,
        "लिंग": "महिला"},
    "11" : {"नाम": "महीपाल",
        "Father": "टोडी सिंह",
        "मकानसंख्या": 2,
        "आयु": 65,
        "लिंग": "पुरुष", },

    "12" : {"नाम": "सुनील कुमार",
     "Father": "महीपाल",
     "मकानसंख्या": 2,
     "आयु": 3,
     "लिंग": "पुरुष", },
    "13" : {"नाम": "ज्योति",
     "Husband": "विकास",
     "मकानसंख्या": 2,
     "आयु": 35,
     "लिंग": "महिला"},

    "14" : {"नाम": "विकास सिंह",
     "Father": "महीपाल सिंह",
     "आयु": 35,
     "लिंग": "पुरुष",
     "मकानसंख्या": 2, },
    "15":{"नाम": "पूनम",
     "Husband": "ओमवीर सिंह",
     "मकानसंख्या": 3,
     "आयु": 29,
     "लिंग": "महिला", },
    "16":{"नाम": "पूकेन्द्र कुमार",
     "Father": "गजेन्द्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 27,
     "लिंग": "पुरुष", },
    "17":{"नाम": "प्रियंका",
     "Husband": "भूपेंद्र कुमार",
     "मकानसंख्या": 3,
     "आयु": 26,
     "लिंग": "महिला", },
    "18":{"नाम": "देवी सिंह",
     "Father": "टोडी सिंह",
     "मकानसंख्या": 3,
     "आयु": 69,
     "लिंग": "पुरुष", },
    "19":{"नाम":  "जगवीर सिंह",
     "Father": "देवी सिंह",
     "मकानसंख्या": 3,
     "आयु": 57,
     "लिंग": "पुरुष", },

    "20":{"नाम":  "शशी",
     "Husband": "जगवीर सिंह",
     "मकानसंख्या": 3,
     "आयु": 55,
     "लिंग": "महिला", },
    "21":{
        "नाम":  "गजेन्द्र सिंह",
        "Father": "देवी सिंह",
        "मकानसंख्या": 3,
        "आयु": 53,
        "लिंग": "पुरुष", },
    "22":{"नाम": "माया देवी",
     "Husband": "गजेन्द्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 52,
     "लिंग": "महिला", },
    "23":{"नाम": "सन्तोष",
     "Husband": "जुगेन्द्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 47,
     "लिंग": "महिला", },
    "24":{"नाम":  "ओमवीर सिह",
     "Father": "गजेन्द्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 31,
     "लिंग": "पुरुष", },
    "25":{"नाम":  "मुनेन्द्र कुमार",
     "Father": "जगवीर सिंह",
     "मकानसंख्या": 3,
     "आयु": 3,
     "लिंग": "पुरुष", },
    "26":{"नाम":  "शिवम चौधरी",
     "Father": "जुगेंद्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 29,
     "लिंग": "पुरुष", },
    "27":{"नाम":  "शिवानी चौधरी",
     "Father": "जुगेन्द्र सिंह",
     "मकानसंख्या": 3,
     "आयु": 24,
     "लिंग": "महिला", },
    "28":{"नाम":  "फतह सिंह",
     "Father": "मोहनलाल",
     "मकानसंख्या": 4,
     "आयु": 55,
     "लिंग": "पुरुष", },

    "29":{"नाम":  "देवेन्द्रसिंह",
     "Father": "रनवीर सिंह",
     "मकानसंख्या": 4,
     "आयु": 52,
     "लिंग": "पुरुष", },

    "30":{"नाम":  "सुरेन्द्र सिंह",
     "Father": "रनवीर सिंह",
     "मकानसंख्या": 4,
     "आयु": 51,
     "लिंग": "पुरुष", }
}

In [142]:
import pandas as pd

In [143]:

df = pd.DataFrame(f)

In [144]:
print(df)

                      1                2          3          4          5  \
नाम         दर्शन चौधरी  राजकुमारी चौधरी   कुवरपाली      जयवीर     नेकराम
Father       हरवीर सिंह              NaN        NaN  पूरन सिंह  पूरन सिंह
मकानसंख्या            0                0          1          1          1
आयु                  26               21         75         47         45
लिंग              पुरुष            महिला      महिला      पुरुष      पुरुष
Husband             NaN      दर्शन चौधरी  पूरन सिंह        NaN        NaN

                 6       7        8          9           10  ...  \
नाम         राजवती    मीता  कर्मवीर  नीतू देवी       संगीता  ...
Father         NaN     NaN     पूरन        NaN          NaN  ...
मकानसंख्या       1       1        1          2            2  ...
आयु             43      40        3         35           36  ...
लिंग         महिला   महिला    पुरुष      महिला        महिला  ...
Husband      जयवीर  नेकराम      NaN    कर्मवीर  सुनील कुमार  ...

                       21             22              23             24  \
नाम         गजेन्द्र सिंह      माया देवी          सन्तोष      ओमवीर सिह
Father          देवी सिंह            NaN             NaN  गजेन्द्र सिंह
मकानसंख्या              3              3               3              3
आयु                    53             52              47             31
लिंग                पुरुष          महिला           महिला          पुरुष
Husband               NaN  गजेन्द्र सिंह  जुगेन्द्र सिंह            NaN

                         25             26              27        28  \
नाम         मुनेन्द्र कुमार     शिवम चौधरी    शिवानी चौधरी  फतह सिंह
Father           जगवीर सिंह  जुगेंद्र सिंह  जुगेन्द्र सिंह   मोहनलाल
मकानसंख्या                3              3               3         4
आयु                       3             29              24        55
लिंग                  पुरुष          पुरुष           महिला     पुरुष
Husband                 NaN            NaN             NaN       NaN

                       29              30
नाम         देवेन्द्रसिंह  सुरेन्द्र सिंह
Father         रनवीर सिंह      रनवीर सिंह
मकानसंख्या              4               4
आयु                    52              51
लिंग                पुरुष           पुरुष
Husband               NaN             NaN

[6 rows x 30 columns]

In [145]:
#0 : dad
#1 : husband
translator = Translator()

name = []
Relation = []
House = []
age = []
gender = []
for i in f:
    
    name.append(translator.translate(f[i]["नाम"]).text)
    if "Father" in f[i]:
        m = '0-'+translator.translate(f[i]["Father"]).text
        Relation.append(m)
    elif "Husband" in f[i]:
        m = '1-'+translator.translate(f[i]["Husband"]).text
        Relation.append(m)
    House.append(translator.translate(f[i]["मकानसंख्या"]).text)
    age.append(translator.translate(f[i]["आयु"]).text)
    gender.append(translator.translate(f[i]["लिंग"]).text)
df = pd.DataFrame(list(zip(name,Relation,House,age,gender)),columns =['Names','Relation','House','age','gender'])

In [146]:
df.to_csv("file1.csv")

In [147]:
import pandas as pd
data = pd.read_csv("PAN.csv")

In [148]:

    
print(data)

    Unnamed: 0                Names             Relation  House  age gender
0            0    Darshan Choudhary      0-Harveer Singh      0   26   Male
1            1  Rajkumari Chaudhary  1-Darshan Choudhary      0   21  Woman
2            2            Kuwarpali        1-Puran Singh      1   75  Woman
3            3              Jaiveer        0-Puran Singh      1   47   Male
4            4               nekram        0-Puran Singh      1   45   Male
5            5              Rajvati            1-Jaiveer      1   43  Woman
6            6                 Mita             1-nekram      1   40  Woman
7            7            Karmaveer        0-Puran Singh      1   37   Male
8            8           Neetu Devi          1-Karmaveer      1   35  Woman
9            9             Sangeeta        1-Sunil Kumar      2   36  Woman
10          10              Mahipal         0-Todi Singh      2   65   Male
11          11          Sunil Kumar            0-Mahipal      2   37   Male
12          12               Jyoti               1-Vikas      2   35  Woman
13          13          Vikas Singh      0-Mahipal Singh      2   35   Male
14          14               Poonam       1-Omveer Singh      3   29  Woman
15          15       pukendra kumar     0-Gajendra singh      3   27   Male
16          16             Priyanka    1-Bhupendra Kumar      3   26  Woman
17          17           Devi Singh         0-Todi Singh      3   69   Male
18          18        Jagveer Singh         0-Devi Singh      3   57   Male
19          19               Shashi      1-Jagveer Singh      3   55  Woman
20          20       Gajendra singh         0-Devi Singh      3   53   Male
21          21            Maya Devi     1-Gajendra singh      3   52  Woman
22          22              Santosh     1-Jugendra Singh      3   47  Woman
23          23         Omveer Singh     0-Gajendra singh      3   31   Male
24          24        Munendr Kumar      0-Jagveer Singh      3   31   Male
25          25     Shivam Choudhary     0-Jugendra Singh      3   29   Male
26          26    Shivani Choudhary     0-Jugendra Singh      3   24  Woman

In [149]:
def relation(count,l,r):
    for i in range(l,r+1):

IndentationError: expected an indented block after 'for' statement on line 2 (257779500.py, line 5)

In [207]:
def relation(y):
    for index,i in y.iterrows():
        print(i)
    print("----------------------------")

In [208]:

for i in range(4):
    r=data.loc[(data.House==i)]
    relation(r)

Unnamed: 0                    0
Names         Darshan Choudhary
Relation        0-Harveer Singh
House                         0
age                          26
gender                     Male
Name: 0, dtype: object
Unnamed: 0                      1
Names         Rajkumari Chaudhary
Relation      1-Darshan Choudhary
House                           0
age                            21
gender                      Woman
Name: 1, dtype: object
Unnamed: 0                2
Names             Kuwarpali
Relation      1-Puran Singh
House                     1
age                      75
gender                Woman
Name: 2, dtype: object
Unnamed: 0                3
Names               Jaiveer
Relation      0-Puran Singh
House                     1
age                      47
gender                 Male
Name: 3, dtype: object
Unnamed: 0                4
Names                nekram
Relation      0-Puran Singh
House                     1
age                      45
gender                 Male
Name: 4, dtype: object
Unnamed: 0            5
Names           Rajvati
Relation      1-Jaiveer
House                 1
age                  43
gender            Woman
Name: 5, dtype: object
Unnamed: 0           6
Names             Mita
Relation      1-nekram
House                1
age                 40
gender           Woman
Name: 6, dtype: object
Unnamed: 0                7
Names             Karmaveer
Relation      0-Puran Singh
House                     1
age                      37
gender                 Male
Name: 7, dtype: object
Unnamed: 0              8
Names          Neetu Devi
Relation      1-Karmaveer
House                   1
age                    35
gender              Woman
Name: 8, dtype: object
Unnamed: 0                9
Names              Sangeeta
Relation      1-Sunil Kumar
House                     2
age                      36
gender                Woman
Name: 9, dtype: object
Unnamed: 0              10
Names              Mahipal
Relation      0-Todi Singh
House                    2
age                     65
gender                Male
Name: 10, dtype: object
Unnamed: 0             11
Names         Sunil Kumar
Relation        0-Mahipal
House                   2
age                    37
gender               Male
Name: 11, dtype: object
Unnamed: 0         12
Names          Jyoti
Relation      1-Vikas
House               2
age                35
gender          Woman
Name: 12, dtype: object
Unnamed: 0                 13
Names             Vikas Singh
Relation      0-Mahipal Singh
House                       2
age                        35
gender                   Male
Name: 13, dtype: object
Unnamed: 0                14
Names                 Poonam
Relation      1-Omveer Singh
House                      3
age                       29
gender                 Woman
Name: 14, dtype: object
Unnamed: 0                  15
Names           pukendra kumar
Relation      0-Gajendra singh
House                        3
age                         27
gender                    Male
Name: 15, dtype: object
Unnamed: 0                   16
Names                  Priyanka
Relation      1-Bhupendra Kumar
House                         3
age                          26
gender                    Woman
Name: 16, dtype: object
Unnamed: 0              17
Names           Devi Singh
Relation      0-Todi Singh
House                    3
age                     69
gender                Male
Name: 17, dtype: object
Unnamed: 0               18
Names         Jagveer Singh
Relation       0-Devi Singh
House                     3
age                      57
gender                 Male
Name: 18, dtype: object
Unnamed: 0                 19
Names                  Shashi
Relation      1-Jagveer Singh
House                       3
age                        55
gender                  Woman
Name: 19, dtype: object
Unnamed: 0                20
Names         Gajendra singh
Relation        0-Devi Singh
House                      3
age                       53
gender                  Male
Name: 20, dtype: object
Unnamed: 0                  21
Names                Maya Devi
Relation      1-Gajendra singh
House                        3
age                         52
gender                   Woman
Name: 21, dtype: object
Unnamed: 0                  22
Names                  Santosh
Relation      1-Jugendra Singh
House                        3
age                         47
gender                   Woman
Name: 22, dtype: object
Unnamed: 0                  23
Names             Omveer Singh
Relation      0-Gajendra singh
House                        3
age                         31
gender                    Male
Name: 23, dtype: object
Unnamed: 0                 24
Names           Munendr Kumar
Relation      0-Jagveer Singh
House                       3
age                        31
gender                   Male
Name: 24, dtype: object
Unnamed: 0                  25
Names         Shivam Choudhary
Relation      0-Jugendra Singh
House                        3
age                         29
gender                    Male
Name: 25, dtype: object
Unnamed: 0                   26
Names         Shivani Choudhary
Relation       0-Jugendra Singh
House                         3
age                          24
gender                    Woman
Name: 26, dtype: object

In [ ]:
""" Darshan Choudhary -----> find(
    1-Darshan Choudhary ------>{name : Rajkumari Chaudhary, Relation : wife},
    0-Darshan Choudhary ----------> if(male) -------> {name : xyz , relation : son} else {name : zyx , relation : daughter}
    find(0-Harveer Singh -------------> {name : abc , relation : if(name) ---> brother else ----> sister})
    1-Harveer Singh ----------> {name : lpq, relation : mother}
    )
Jaiveer ----->  find(
    1-Jaiveer -------> {name : Rajvati,relation : wife}
    0-Jaiveer -------->if(male) -------> {name : xyz , relation : son} else {name : zyx , relation : daughter}
    find(0-Puran Singh ---------> {name : nekram,relation brother} else: if(female) : sister)
    find(1-Puran Singh ---- > {name : Kuwarpali,Relation : mother})
) """

"""s = 0
m = 2
l = 0
for i in range(26):
    count = data['House'].value_counts()[int(data.iloc[i,[3]])]
    
    if(s==0):
       s =int(data.iloc[i,[0]])+count-1
       m = int(data.iloc[i,[0]])+count-1
    else:
        s = m-i
    relation(count,int(data.iloc[i,[0]]),m)"""

In [ ]:
import pandas as pd
data1 = pd.read_csv("PAN.csv")

In [ ]:
df_group=data1.groupby(['House','Names'])
df_group.head()

    Unnamed: 0                Names             Relation  House  age gender
0            0    Darshan Choudhary      0-Harveer Singh      0   26   Male
1            1  Rajkumari Chaudhary  1-Darshan Choudhary      0   21  Woman
2            2            Kuwarpali        1-Puran Singh      1   75  Woman
3            3              Jaiveer        0-Puran Singh      1   47   Male
4            4               nekram        0-Puran Singh      1   45   Male
5            5              Rajvati            1-Jaiveer      1   43  Woman
6            6                 Mita             1-nekram      1   40  Woman
7            7            Karmaveer        0-Puran Singh      1   37   Male
8            8           Neetu Devi          1-Karmaveer      1   35  Woman
9            9             Sangeeta        1-Sunil Kumar      2   36  Woman
10          10              Mahipal         0-Todi Singh      2   65   Male
11          11          Sunil Kumar            0-Mahipal      2   37   Male
12          12               Jyoti               1-Vikas      2   35  Woman
13          13          Vikas Singh      0-Mahipal Singh      2   35   Male
14          14               Poonam       1-Omveer Singh      3   29  Woman
15          15       pukendra kumar     0-Gajendra singh      3   27   Male
16          16             Priyanka    1-Bhupendra Kumar      3   26  Woman
17          17           Devi Singh         0-Todi Singh      3   69   Male
18          18        Jagveer Singh         0-Devi Singh      3   57   Male
19          19               Shashi      1-Jagveer Singh      3   55  Woman
20          20       Gajendra singh         0-Devi Singh      3   53   Male
21          21            Maya Devi     1-Gajendra singh      3   52  Woman
22          22              Santosh     1-Jugendra Singh      3   47  Woman
23          23         Omveer Singh     0-Gajendra singh      3   31   Male
24          24        Munendr Kumar      0-Jagveer Singh      3   31   Male
25          25     Shivam Choudhary     0-Jugendra Singh      3   29   Male
26          26    Shivani Choudhary     0-Jugendra Singh      3   24  Woman

In [ ]:
search_val={"Name":"Darshan Choudhary","age":26}
search_val

{'Name': 'Darshan Choudhary', 'age': 26}

In [ ]:
house=data1['House'].where(data1['Names']==search_val['Name'] +data1['Relation'])

In [ ]:
rel1='0-'+search_val['Name']
rel2='1-'+search_val['Name']
rel2

'1-Darshan Choudhary'

In [ ]:
data.loc[data1['Relation']== rel1,'new_rel']= 'Son'

In [ ]:
df = df['House'].apply x: 'True' if x ==0 else 'False')
# data1 use krna aab(

TypeError: string indices must be integers

In [176]:
df=data.loc[(data.House==0)]

In [200]:
relat={search_val['Name']:{}}
for i in range(len(df)):
    if df.loc[i]['Relation']==rel1:
        relat[search_val]['Name']['name']=df.loc[i]['Names']
        relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
    elif df.loc[i]['Relation']==rel2:
        relat[search_val]['Name']['name']=df.loc[i]['Names']
        relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
        
relat

<>:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
<>:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
<>:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
<>:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:5: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]['name']]['relation']='Son'
C:\Users\lokes\AppData\Local\Temp\ipykernel_12932\2879547568.py:8: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  relat[[search_val]['Name']][df.loc[i]]['relation']='Daughter'

TypeError: unhashable type: 'dict'